version: "3.9"

services:
  cardgame-server:
    build: ./server
    container_name: cardgame-server
    ports:
      - "8600:8600"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  cardgame-client:
    build: ./client
    container_name: cardgame-client
    ports:
      - "3600:80"
    depends_on:
      - cardgame-server
    restart: unless-stopped
